### ISSUE TITLE
Sending screenshot in 1-on-1 chat doesn't work

### ISSUE THREAD

**Issue by sunleos** [status-im/status-desktop#18624]
# Bug Report

## Steps to reproduce
1. open a 1-on-1 conversation
2. make a screenshot 
3. paste it in the input bar and type some text
4. hit enter/send

#### Expected behavior
the message with the pasted screenshot it sent

#### Actual behavior
the message with the screenshot disappeared and the message input field in this particular 1-on-1 DM is blocked 

<img width="1539" height="276" alt="Image" src="https://github.com/user-attachments/assets/ca5cccf3-da44-4030-8b78-52be2cff5608" />

### Additional Information
the message input field in the other 1-on-1 conversations work fine (i.e. let you input data there)
- 
- Status desktop version: v2.35 RC4
- Operating System: Windows 10

**Comment by caybro** [comment]
I have a dejavu here @jrainville, I thought we had the bug before and fixed it :)

**Comment by caybro** [comment]
> > I have a dejavu here [@jrainville](https://github.com/jrainville), I thought we had the bug before and fixed it :)
> 
> Indeed. I did fix that in an RC of 2.34.
> 
> I'm not sure why it regressed.
> 
> In my case, it also fails, but at least I have an error message: 
> 
> <img width="1918" height="912" alt="Image" src="https://github.com/user-attachments/assets/efb4bbd1-cbc3-43ac-99ff-361942f44616" />

Maybe it was fixed only in the release branch?

**Comment by jrainville** [comment]
Good question. I did make two PRs

master PR https://github.com/status-im/status-desktop/pull/18182
release PR: https://github.com/status-im/status-desktop/pull/18219

We just need to double check if the fix is still there. Seeing the logs, it does seem like the fix was reverted or removed by accident, because we should be passing a file path to status-go and not a data path

**Comment by anastasiyaig** [comment]
we do have a case with sending picture in chat, what we dont have is pasting it with clipboard. Yes, there is a task @jrainville https://github.com/status-im/status-desktop/issues/18211

**Comment by caybro** [comment]
> Ah, it seems like a change because of QT6. The regex we use for detecting base64 images doesn't catch the image path QT gives us anymore!

What was/is the URL?

**Comment by jrainville** [comment]
Reopening because it still happens on Windows and on Mac according to Nastya (https://github.com/status-im/status-desktop/issues/18211#issuecomment-3224083926)

I have a repro on Windows, so I'll fix again

**Comment by jrainville** [comment]
The issue on Windows seems to be with the JSON string itself that is sent to the thread:

```
ERR 2025-08-26 15:17:46.489Z [threadpool task thread] parsing task arg  topics="task-threadpool" tid=20876 file=threadpool.nim:54 error="input(1, 5911) Error: } expected"
```

**Comment by jrainville** [comment]
Ok found it. The temp dir has backslashes in it because it's a Windows path `C:\Users\sur_e\AppData\Local\Status\tmp\`

Those need to be escaped
