### ISSUE TITLE
The profile image doesn't look good on the onboarding page

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5241]
# Bug Report

## Steps to reproduce

1. Launch the app
3. Hit "I'm new to Status" - "Generate new keys"
4. Hit "+" and upload the photo from the attachment to this issue
5. Hit "Done"
6. Check the profile picture
![camera_test_apple_563728](https://user-images.githubusercontent.com/14942081/160524540-bd801d2c-6b97-4fb9-857e-950ca1099f80.jpeg)

#### Expected behavior
The profile picture is shown in full of the circle shape
#### Actual behavior
The profile picture is shown with white borders
<img width="485" alt="image" src="https://user-images.githubusercontent.com/14942081/160524216-f85b0b84-d11b-4b52-aeea-aa3eac34672d.png">

### Additional Information

- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

**Comment by iurimatias** [comment]
to fix this, a qt update is needed

**Comment by elina2015** [comment]
@saledjenic hey, now the image is not shown with white borders, but it's blurred. Could you kindly check the video?

https://user-images.githubusercontent.com/14942081/162356352-7cd8b032-3c1b-473c-8094-f310e18f4209.mov

**Comment by saledjenic** [comment]
> Could you kindly check the video?

@elina2015 I checked and fixed the issue you found, thank you.

**Comment by elina2015** [comment]
@saledjenic hey, I found the profile picture doesn't look good and it's not saved as a profile picture. Could you kidly check it?
**Steps:**
1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Hit "+" and upload the photo from the attachment to this issue or another one
4. Hit "x" for cropping dialogue
5. Hit 'Done' for Profile picture dialogue

**Actual Result:**
The picture is shown incorrectly - with top and bottom borders and it is not saved, while the cropping is optional.
https://user-images.githubusercontent.com/14942081/162605394-e3d52228-7e1b-4eb8-8e1d-b9f39a771b9e.mov

**Expected Result:**
The profile picture is saved correctly

**Comment by elina2015** [comment]
Test run for QA: https://ethstatus.testrail.net/index.php?/runs/view/8945

**Comment by saledjenic** [comment]
@elina2015 thanks for all this... as of `#1` I am not sure what happened since I tested that :), `#2` was something I didn't touch most likely that behaviour is the same as it's in the master.

Anyhow, please recheck it again since I fixed `#1` and `#2` and rebased it on the latest master, so all should be good now.

**Comment by endulab** [comment]
Hmm, If this that this task should cover ? 
![image](https://user-images.githubusercontent.com/61889657/162729120-c7b420dd-1146-41f5-80f2-ffe37bd5d5d3.png)

I am not sure @elina2015 @saledjenic

**Comment by saledjenic** [comment]
@endulab that's perfectly fine if you didn't crop the image. Your image has much higher height than width, and we display it using `KeepAspectRatio` so all good. If you cropped it, then height and width would be the same and the whole circle would be fulfilled in that case.

**Comment by elina2015** [comment]
@saledjenic thank you so much for the updates, but the bug  #1 is still reproduced (tested on the PR https://github.com/status-im/status-desktop/pull/5392 and the latest master):
**The image is not saved as a profile picture if the user didn't crop it on the onboarding screen**
**Steps:**
1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Hit "+" and upload the photo from the attachment to this issue or another one
4. Hit "x" for cropping dialogue
5. Hit 'Done' for Profile picture dialogue
6. Finish onboarding and check the profile picture in Settings-Profile

**Actual Result:**
The picture is not saved

https://user-images.githubusercontent.com/14942081/162825723-359ee5e5-3cce-422e-87bf-b0545e1dbae3.mov


**Expected Result:**
The profile picture is saved correctly

Could you kindly check?

**Comment by saledjenic** [comment]
@elina2015 I analyzed a bit that flow and realized that the flow is incorrect, it somehow ignores the buttons, for example once you select the image it is set for the profile, instead to be set only if user confirms that clicking on a "Done" button. Also we're letting user to set profile image in a native ratio, which is not good at all, that makes our design ugly, and that's actually why we do have "crop" feature.

So based on above I see the following as requirements for setting the profile image (we can ask @iurimatias to confirm):
- If user wants to set custom image as profile image, it must be cropped (must have the same width and hight)
- Click on a "+" button always opens "Upload profile picture" popup without any selected image (so this popup is always empty when we open it since it will be opened only if user wants to upload image). 
- Uploading new image from within "Upload profile picture" popup can be done either clicking on an empty circle (where selected image should appear) or clicking "Upload" button. That action should open `FileDialog` so a user can select desired image.
- Once image is selected "Crop Popup" should be opened, where user will be able to select portion of the image he wants to use as profile image, and image will be uploaded only if "Finish" button is clicked. In any other case we ignore that image (that way we force him to crop the image).
- Once "Finish" button is clicked cropped image will be previewed in "Upload profile picture" popup, allowing user either to select image again or confirm clicking "Done" button that he wants to use what he sees there as his profile image.
- Profile image should be changed only if user clicks "Done" button from "Upload profile picture" popup (if that popup gets closed in any other way profile image should be the same as it was before opening this popup)

I think the above should be all use cases for selecting profile image from the onboarding screen. If you agree, please open new ticket with the same requirements for selecting profile image from `Settings -> Profile` page, since those 2 should follow the same use cases.

@elina2015 changes currently done in PR #5392 follow above described use cases, please test that.

**Comment by saledjenic** [comment]
@endulab that issue is fixed here as well, also things around the image and cropping are aligned to the above described flow.

**Comment by elina2015** [comment]
@saledjenic this requirement doesn't work now:
_Profile image should be changed only if the user clicks "Done" button from "Upload profile picture" popup (if that popup gets closed in any other way profile image should be the same as it was before opening this popup)_

I will add a separate task for it too.

**Comment by saledjenic** [comment]
@elina2015 it does work for me, check this [video](https://drive.google.com/file/d/12TQ5zY2Cgkz0-oJ2d01yxPaL85s0seDy/view?usp=sharing). Or let me know what did you do it?
