### ISSUE TITLE
Communities: 'Pending' is shown after joining a public community

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7949]
# Bug Report

## Steps to reproduce
1. Go to Communities Portal and click on 'CryptoParty from Elina' (it's a public community)
2. In the opened community (top left corner) click on the button for joining
3. Accept the rules
4. Check the appeared notification and the text on the Joining button (left top corner)

#### Expected behavior
As the community is public, users should be able to join without acceptance from the community owner
#### Actual behavior
The button shows 'Pending' and in the notification, there is 'Your request has been submitted' appeared while the community is public
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/14942081/196584256-c1c364eb-446a-44fa-b51e-5fa045edaf23.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/228/
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
@borismelnik this is fixed/changed with the new community join workflow right?

**Comment by borismelnik** [comment]
@jrainville yes, no `Pending` anymore, there should be `Membership request is pending`, but I can't check it, cos I can't find this community. I test it on latest master for public community - notification still appeared. Will fix.

**Comment by jrainville** [comment]
I thin this issue is the wanted behavior. As discussed here https://github.com/status-im/status-desktop/pull/8399#issuecomment-1324648818, it's normal for the open communities to still need a request. Shall we close it @iurimatias ?
